export const UPDATE_CART = 'UPDATE_CART';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const SET_LOADED_PRODUTOS = 'SET_LOADED_PRODUTOS';
export const ON_LOAD_PRODUTOS = 'ON_LOAD_PRODUTOS';